### PR TITLE
Remove obsolete AppVeyor and Travis-CI config files

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
Is anyone maintaining this? @rfourquet perhaps?

**Comment by ViralBShah** [comment]
Just noticed this.

**Comment by fingolfin** [comment]
Thanks @ViralBShah maybe you can also merge #16 ?

**Comment by ViralBShah** [comment]
@rfourquet I have invited @fingolfin to this org, so that we can have an extra pair of hands to fix some regular maintenance issues.

**Comment by rfourquet** [comment]
Sounds good! yes Removing AppVeyor and Travis was good, it's just for enabling CodeCov (#16) that I want to look closer first.

**Comment by fingolfin** [comment]
@rfourquet of course

**Comment by rfourquet** [comment]
No pb, yes I've neglected updates to the repo, but `RandomExtensions` is very much not dead, I've a bunch of local changes, which just need some free time to be cleaned up. I think the most useful coming change is to split apart pirating and non-pirating stuff in distinct packages, so that useful stuff from `RandomExtensions` can be used without relying on a pirating package.

**Comment by ViralBShah** [comment]
@fingolfin I have given you ownership of the org. Ideally we should probably have something between member and committer.

**Comment by fingolfin** [comment]
Thanks @ViralBShah. That's of course the highest possible access level. I've used it to install the Codecov app, and will look into making that work. Of course if it is deemed that restriction access to fewer people is better, I won't complain if that access level is reduced.

**Pull request merged**
